argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
  controller:
    persistence:
      enabled: true
      size: 10Gi               # Size of the Persistent Volume
      storageClassName: gp2     # Set this according to your storage class
      accessModes:
        - ReadWriteOnce
      annotations: {}

  redis:
    enabled: true
    persistence:
      enabled: true
      size: 5Gi                # Size for Redis Persistent Volume
      storageClassName: gp2     # Set this according to your storage class
      accessModes:
        - ReadWriteOnce
